### BUY_ITEM payment
< {% import { signCapitalistRequest } from "../../sign-capitalist.js"; signCapitalistRequest(request, crypto); %}
POST {{baseUrl}}/v1/payment
API-Key: {{apiKey}}
X-Request-Timestamp: {{timestamp}}
Signature: {{signature}}
Content-Type: application/json

{
  "userRequestId": "buy-item-{{$timestamp}}",
  "accountFrom": "{{fromAccount}}",
  "amount": 13.45,
  "currency": "{{currency}}",
  "comment": "BUY_ITEM payment example",
  "payload": {
    "productId": {{prepaidProductId}},
    "denominationId": {{prepaidDenominationId}},
    "type": "BUY_ITEM"
  }
}
