### MEGAFON mobile payment
< {% import { signCapitalistRequest } from "../../sign-capitalist.js"; signCapitalistRequest(request, crypto); %}
POST {{baseUrl}}/v1/payment
API-Key: {{apiKey}}
X-Request-Timestamp: {{timestamp}}
Signature: {{signature}}
Content-Type: application/json

{
  "userRequestId": "megafon-{{$timestamp}}",
  "accountFrom": "{{fromAccount}}",
  "amount": 100,
  "currency": "{{currency}}",
  "comment": "MEGAFON payout example",
  "payload": {
    "type": "MEGAFON",
    "account": "79001234567"
  }
}
