### WM payment
< {% import { signCapitalistRequest } from "../../sign-capitalist.js"; signCapitalistRequest(request, crypto); %}
POST {{baseUrl}}/v1/payment
API-Key: {{apiKey}}
X-Request-Timestamp: {{timestamp}}
Signature: {{signature}}
Content-Type: application/json

{
  "userRequestId": "wm-{{$timestamp}}",
  "accountFrom": "{{fromAccount}}",
  "amount": 100,
  "currency": "{{currency}}",
  "comment": "WM payout example",
  "payload": {
    "type": "WM",
    "account": "9876543210"
  }
}
