### Get payment by user request ID
< {% import { signCapitalistRequest } from "../../sign-capitalist.js"; signCapitalistRequest(request, crypto); %}
GET {{baseUrl}}/v1/payment/{{userRequestId}}
API-Key: {{apiKey}}
X-Request-Timestamp: {{timestamp}}
Signature: {{signature}}
