### BITCOIN payment
< {% import { signCapitalistRequest } from "../sign-capitalist.js"; signCapitalistRequest(request, crypto); %}
POST {{baseUrl}}/v1/payment
API-Key: {{apiKey}}
X-Request-Timestamp: {{timestamp}}
Signature: {{signature}}
Content-Type: application/json

{
  "userRequestId": "bitcoin-{{$timestamp}}",
  "accountFrom": "{{fromAccount}}",
  "amount": 100,
  "currency": "{{currency}}",
  "comment": "BITCOIN payout example",
  "payload": {
    "type": "BITCOIN",
    "account": "bc1qxy2kg342rsqtzq2n0yrf2493p83kkfjhx0wlh"
  }
}
