### Get merchant orders
< {% import { signCapitalistRequest } from "../sign-capitalist.js"; signCapitalistRequest(request, crypto); %}
GET {{baseUrl}}/v1/orders?limit=100&offset=0
API-Key: {{apiKey}}
X-Request-Timestamp: {{timestamp}}
Signature: {{signature}}
